#spring:
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://127.0.0.1:3306/examSystem?useUnicode=true&characterEncoding=utf8
#    driver-class-name: com.mysql.cj.jdbc.Driver


#spring集成Mybatis环境
#mybatis:
#  #pojo别名扫描包
#  type-aliases-package: com.hnust.domain
#  #驼峰命名转化
#  configuration:
#    map-underscore-to-camel-case: true

retrofit:
  baseUrl: "http://localhost:8000"
  enable-response-call-adapter: true
  # 启用日志打印
  enable-log: true
  # 连接池配置
  pool:
    test1:
      max-idle-connections: 3
      keep-alive-second: 100
    test2:
      max-idle-connections: 5
      keep-alive-second: 50
  # 禁用void返回值类型
  disable-void-return-type: false
  # 日志打印拦截器
  logging-interceptor: com.github.lianjiatech.retrofit.spring.boot.interceptor.DefaultLoggingInterceptor
  # 请求重试拦截器
  retry-interceptor: com.github.lianjiatech.retrofit.spring.boot.retry.DefaultRetryInterceptor
  # 全局转换器工厂
  global-converter-factories:
    - retrofit2.converter.jackson.GsonConverterFactory
  # 全局调用适配器工厂
  global-call-adapter-factories:
    - com.github.lianjiatech.retrofit.spring.boot.core.BodyCallAdapterFactory
    - com.github.lianjiatech.retrofit.spring.boot.core.ResponseCallAdapterFactory

#设置窗口参数，注意：stage只有一个
javafx:
  title: "出卷系统"
  appicons: /image/app2.png